<MobiOutputSettingUi>
    tf_file_type: tf_file_type
    tf_personal_doc: tf_personal_doc
    MDTextField:
        id: tf_file_type
        hint_text: "Mobi file type(Unsupported for now)"
        helper_text: "old, new or both"
        helper_text_mode: "on_focus"
        disabled: True
    MDTextField:
        id: tf_personal_doc
        hint_text: "--personal-doc"
        helper_text: "Tag for MOBI files to be marked as personal documents."
        helper_text_mode: "on_focus"